{% set name = "sbtab" %}
{% set version = "0.9.78" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sbtab-{{ version }}.tar.gz
  sha256: b071ea2d9831827766bd6b7451ec244d97e24ac288423d6dcf395dc6955b4812

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - numpy >=1.16.2
    - openpyxl <=2.6.4
    - pandas >=0.2
    - python >=3.0
    - python-libsbml >=5.17.0
    - scipy >=1.0

test:
  imports:
    - sbtab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.sbtab.net
  dev_url: https://github.com/tlubitz/SBtab
  summary: SBtab - Standardised Data Tables for Systems Biology
  license: MIT
  license_file: LICENSE
  description: >
    Handles I/O and creation of SBtab tables and documents, a standardised Systems Biology file format for simple yet structured data exchange.

extra:
  recipe-maintainers:
    - eladnoor
    - tlubitz
